compatibility_date = "2025-01-08"
main = "src/index.ts"
name = "b-movie-woker"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_id = "d9fc16d3-7b47-4602-9eba-2387ccabfe1d"
database_name = "b-movie-db"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
